default: &default
  adapter: cockroachdb
  user: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 26257
  host: localhost
  database: orbital_defence_development

test:
  <<: *default
  database: orbital_defence_test
  port: 26257
#  user: <%#= ENV['DB_USER'] %>
#  password: <%#= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

production:
  <<: *default
  url: <%= ENV['DOKKU_POSTGRES_BLACK_URL'] %>
