default: &default
  adapter: cockroachdb
  user: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 26257
  host: localhost
  database: orbital_defence_development

test:
  <<: *default
  port: 26257
  host: localhost
  database: orbital_defence_test

production:
  <<: *default
  database: orbital_defence_production
  user: ENV['DB_USER']
  password: ENV['DB_PASSWORD']
  host: 206.189.130.62
