default: &default
  :reconnect_attempts: 3
  :timeout: 2

development:
  <<: *default
  :host: <%= ENV['REDIS_URL'] || 'localhost:6379' %>
  :port: <%= ENV['REDIS_PORT'] || 6379 %>
  :db: 12


test:
  <<: *default
  :host: <%= ENV['REDIS_URL'] || 'localhost:6379' %>
  :port: <%= ENV['REDIS_PORT'] || 6379 %>
  :db: 12

production:
  <<: *default
  :url: <%= ENV['REDIS_URL'] || 'localhost:6379' %>

