default: &default
  :connect_timeout: 5
  :read_timeout: 1
  :write_timeout: 1
  :reconnect_attempts: 3
  :timeout: 1
  :expires_in: 600

development:
  <<: *default
  :host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  :port: <%= ENV['REDIS_PORT'] || 6379 %>
  :db: 12

test:
  <<: *default
  :host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  :port: <%= ENV['REDIS_PORT'] || 6379 %>
  :db: 12

production:
  <<: *default
  :host: <%= ENV['REDIS_HOST']%>
  :port: <%= ENV['REDIS_PORT']%>
  :password: <%= ENV['REDIS_PASSWORD']%>
  :db: 0

