development: &development
  :host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  :port: <%= ENV['REDIS_PORT'] || 6379 %>
  :db: 12
  :reconnect_attempts: 3
  :timeout: 2

test:
  <<: *development

production:
  <<: *development
