default: &default
  import_weather:
    class: WeatherImportWorker
    every: "1h"
    queue: low
    description: Import Weather Data

  import_fires:
    class: FirmsImportWorker
    every: "1h"
    queue: low
    description: Import Fire Data

test:

development:
  <<: *default

production:
  <<: *default
